// <auto-generated />
using System;
using HelpdeskApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpdeskApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615032136_AddPriorityAndUnread")]
    partial class AddPriorityAndUnread
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HelpdeskApp.Models.Entities.FollowUpNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TicketRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TicketRequestId");

                    b.ToTable("FollowUpNotes");
                });

            modelBuilder.Entity("HelpdeskApp.Models.Entities.TeamMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("HelpdeskApp.Models.Entities.TicketRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedResource")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentName")
                        .HasColumnType("TEXT");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasUnreadUserMessage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QueueNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TargetDelivery")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TicketRequests");
                });

            modelBuilder.Entity("HelpdeskApp.Models.Entities.FollowUpNote", b =>
                {
                    b.HasOne("HelpdeskApp.Models.Entities.TicketRequest", "TicketRequest")
                        .WithMany("FollowUpNotes")
                        .HasForeignKey("TicketRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TicketRequest");
                });

            modelBuilder.Entity("HelpdeskApp.Models.Entities.TicketRequest", b =>
                {
                    b.Navigation("FollowUpNotes");
                });
#pragma warning restore 612, 618
        }
    }
}
